# Generated by Django 3.2.7 on 2021-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host1', models.CharField(max_length=50)),
                ('host2', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
    ]
