# Generated by Django 3.2.7 on 2021-12-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
