# Generated by Django 3.2.7 on 2021-12-05 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_hosting_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
