# Generated by Django 3.2.7 on 2022-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_hosting_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
