# Generated by Django 3.2.7 on 2022-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='hosting',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='room_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='host1',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='host2',
            field=models.GenericIPAddressField(),
        ),
    ]
