# Generated by Django 3.2.7 on 2022-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20220225_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('message', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('host1', models.GenericIPAddressField()),
                ('host2', models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
