# Generated by Django 4.0.4 on 2022-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
