# Generated by Django 4.0.4 on 2022-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_thread_user_alter_thread_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
