# Generated by Django 4.0.4 on 2022-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_delete_thread_remove_room_id_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
