# Generated by Django 4.0.4 on 2022-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_hosting_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='host2',
            field=models.CharField(max_length=20),
        ),
    ]
